### ISSUE TITLE
Create a skeletal version of individual Project Portfolio Page (PPP)

### ISSUE THREAD

**Issue by zzhikai** [AY2122S2-CS2103T-T09-2/tp#10]
- Just the headings are enough. You can write to be added soon as placeholders for content.
- PDF conversion not required.
- Follow the details in website

**Comment by ryantanlien** [comment]
Added my skeletal PPP, made the PR as well.

**Comment by RyanCheungJF** [comment]
Done as well, team lead please [review](https://github.com/AY2122S2-CS2103T-T09-2/tp/pull/23). Thanks!
