### ISSUE TITLE
[PE-D] Unclear use of "input" in the User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-2/tp#172]
![Screenshot 2022-04-01 at 2.06.29 PM.png](https://raw.githubusercontent.com/kerbysoh/ped/main/files/8827df3d-cce1-4374-b076-10b1707901a6.png)

It is unclear what input here refers to. In my mind, inputs refer to the entire user input. This should be more clearly defined in the User Guide.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: kerbysoh/ped#1

**Comment by ryantanlien** [comment]
Fixed with #235
