### ISSUE TITLE
[PE-D] Multiple persons with the same email can be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-2/tp#173]
![image.png](https://raw.githubusercontent.com/ovidharshini/ped/main/files/1a660233-c866-4bf2-8924-b78016ada873.png)

I'm not fully certain if this counts as a bug but multiple people can have the same email. Considering the context for this being recruiting, it doesn't appear to make sense to have the same contact information for multiple people? I'm not sure of this though. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ovidharshini/ped#3

**Comment by zzhikai** [comment]
feature flaw, cant fix
