### ISSUE TITLE
[PE-D] Quick Start does not work using Mac devices

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-2/tp#174]
![Screenshot 2022-04-01 at 2.09.33 PM.png](https://raw.githubusercontent.com/kerbysoh/ped/main/files/3a80c48f-8e96-4b89-8255-75a4a9348e3e.png)

Following the Quick Start, I am unable to run the .jar file after double clicking it on a Macbook. The relevant folders are not correctly created. 

-------------
Labels: `severity.High` `type.DocumentationBug`
original: kerbysoh/ped#2

**Comment by zzhikai** [comment]
Actual bug in macOS
