### ISSUE TITLE
[PE-D] View command only allows exact name searching

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-2/tp#195]
Under the UG and testing,  the view command only allows searching if you have the exact name. However, what if someone has a long name, or you do not remember their surname? Searching by Steve does not return Steve Jobs, but I feel it should be a basic feature of the find command, especially if there are many contacts

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: brian16600/ped#7

**Comment by zzhikai** [comment]
Intended behaviour
