### ISSUE TITLE
[PE-D] Phone numbers can be very long

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-2/tp#198]
![image.png](https://raw.githubusercontent.com/ovidharshini/ped/main/files/ac6da42b-4f7f-494f-b39a-35bbcb9744e3.png)

Maybe there should be some level of checks for the length? The label 'Phone: ' also disappears when the phone number is too long, and the number gets cut off at either sides, which is probably undesirable behaviour but not behaviour that probably needs to be tested for if the validation for phone numbers are sufficient. 

For this bug, it is either the phone number length that is the bug or the 'Phone: ' text disappearing and the number getting cut off is a bug. It is your team's choice to decide on which one you prefer to account for in your code, but as long as one of them is resolved, the other should be taken care of. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ovidharshini/ped#6

**Comment by zzhikai** [comment]
regex for max number of input
