### ISSUE TITLE
[PE-D] Name field display is not wrapped for very long names with small window size

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-2/tp#207]
![image.png](https://raw.githubusercontent.com/ovidharshini/ped/main/files/ad4a815e-34c7-494d-83de-a9919135da65.png)

A very long name might not be fully visible in the smallest window size, even if the name in this test input is clearly unrealistic and the odds of encountering a sufficiently long name is rather low. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ovidharshini/ped#11

**Comment by ryantanlien** [comment]
Set max character limit to 50
