### ISSUE TITLE
[PE-D] Sort Error Message

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-2/tp#214]
![Screenshot 2022-04-01 at 8.28.08 PM.png](https://raw.githubusercontent.com/seksek13/ped/main/files/a1338787-e4c3-4670-aa39-b80cabff5d1c.png)

When supplied with invalid prefix, app does not prompt user about the invalid command. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: seksek13/ped#5

**Comment by zzhikai** [comment]
Provide valid command example
